### ISSUE TITLE
Is this still being updated?

### ISSUE THREAD

**Issue by johnmildinhall** [DavidBeavan/coronavirus_covid-19#11]
Hi David,

this is really helpful for my organisation's work supporting C19 response. I was wondering if you are going to continue updating it? I notice that the latest data is 30 March. No worries if not, but would be good to know. 

Thanks!

**Comment by DavidBeavan** [comment]
I'm so glad this is useful, thanks for the kindly prod

I will push out another update when we get the government stats are released today, so mid/late evening. I had some tweaks developed locally, so that explains the silence.

Can I ask how you're using this and what aspects are important for your organisation, so I get a feel for what needs more work? Feel free to make suggestions/issues or if you like, get stuck in with the code yourself.

**Comment by DavidBeavan** [comment]
Updated to 2020-04-02, fresh data just released
